version: '3.8'

networks:
  app_net:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
      - POSTGRES_HOST=postgres
      - REDIS_ADDR=redis:6379
      - NATS_URL=nats://nats:4222

  subscriber:
    build: .
    command: ["./subscriber"]
    networks:
      - app_net
    depends_on:
      nats:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      - NATS_URL=nats://nats:4222
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=testdb

  postgres:
    image: postgres:13-alpine
    networks:
      - app_net
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    networks:
      - app_net
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2-alpine
    networks:
      - app_net
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8222/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=testdb
    networks:
      - app_net
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./migrations/clickhouse:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - 'http://localhost:8123/' | grep -c 'Ok.' > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  clickhouse_data: